language: java
script: mvn install -P remote
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY_ID
  region: eu-west-2
  app: My First Elastic Beanstalk Application
  zip_file: target/the-bedazzled-1.0.48-SNAPSHOT.war
  env: bedazzled-web
  bucket_name: elasticbeanstalk-eu-west-2-307854530528
  on:
    repo: grandjambon/the-bedazzled
    branch: master